# Author: Koushik Sen (ksen@berkeley.edu)
# Contributors:
# Koushik Sen (ksen@berkeley.edu)
# add your name here
"""Bridge live tool callables to the ``kiss.server.sorcar.run`` API.

The synchronous client API :func:`kiss.server.sorcar.run` takes extra
agent tools as a *file path*: the daemon imports the Python file and
registers its top-level public functions (see
:mod:`kiss.server.tools_file`).  Third-party agents, however, supply
LIVE callables — bound backend methods holding authenticated clients
and per-message ``reply`` closures — which cannot be written into a
static file.

This bridge closes the gap for the in-process daemon the third-party
launcher runs (:mod:`._kiss_web_launcher`):

1. :func:`register_tools` stores the live callables in a process-global
   registry under a fresh token and generates a real tools file whose
   genuine top-level ``def`` wrappers mirror each callable's name,
   signature (annotations rendered as string literals under ``from
   __future__ import annotations``; keyword-only markers preserved) and
   docstring (assigned post-``def`` from the registry — no source
   escaping).  Default values are hoisted into module-level variables
   fetched from the registry at import time, so the wrapper carries the
   ORIGINAL default objects by identity, not a repr copy.
2. The daemon's :func:`kiss.server.tools_file.load_tools_file` imports
   the generated file — in the same process — so each wrapper's body,
   ``dispatch(token, name, kwargs)``, reaches this module's registry
   and invokes the live callable with the agent's arguments.
3. :func:`release_tools` invalidates the token and deletes the file
   once the task is over.
"""

from __future__ import annotations

import ast
import inspect
import shutil
import tempfile
import threading
import uuid
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any

_SUPPORTED_KINDS = (
    inspect.Parameter.POSITIONAL_OR_KEYWORD,
    inspect.Parameter.KEYWORD_ONLY,
)

# token -> {"tools": {name: callable}, "dir": generated-file directory}.
_REGISTRY: dict[str, dict[str, Any]] = {}
_REGISTRY_LOCK = threading.Lock()

_HEADER = '''\
"""Auto-generated tools file bridging to live third-party agent tools.

Generated by kiss.agents.third_party_agents._api_tools_bridge for one
task run; each top-level function dispatches to the live callable
registered in the launching process.  Deleted when the task ends.
"""

from __future__ import annotations

from kiss.agents.third_party_agents import _api_tools_bridge as _bridge

_TOKEN = {token!r}
'''


def _entry(token: str) -> dict[str, Any]:
    """Return the registry entry for *token*.

    Args:
        token: A token minted by :func:`register_tools`.

    Returns:
        The registry entry mapping.

    Raises:
        RuntimeError: When the token is unknown (never registered, or
            already released because its task finished).
    """
    with _REGISTRY_LOCK:
        entry = _REGISTRY.get(token)
    if entry is None:
        raise RuntimeError(
            f"tools token {token!r} is not registered (the launching "
            f"task has finished and its live tools were released)"
        )
    return entry


def _live_tool(token: str, name: str) -> Callable[..., Any]:
    """Return the live callable registered as *name* under *token*.

    Args:
        token: A token minted by :func:`register_tools`.
        name: The tool name.

    Returns:
        The registered callable.

    Raises:
        RuntimeError: When the token or the tool name is unknown.
    """
    tools: dict[str, Callable[..., Any]] = _entry(token)["tools"]
    fn = tools.get(name)
    if fn is None:
        raise RuntimeError(f"no live tool named {name!r} for token {token!r}")
    return fn


def dispatch(token: str, name: str, kwargs: dict[str, Any]) -> Any:
    """Invoke the live callable behind a generated wrapper.

    Called by the generated tools file's wrapper bodies with the
    wrapper's bound parameters.

    Args:
        token: The registration token embedded in the generated file.
        name: The tool name.
        kwargs: The wrapper's bound arguments.

    Returns:
        Whatever the live callable returns.

    Raises:
        RuntimeError: When the token or the tool name is unknown.
    """
    return _live_tool(token, name)(**kwargs)


def tool_default(token: str, name: str, param: str) -> Any:
    """Return the original default object of a tool parameter.

    Called at import time of the generated tools file so the wrappers
    carry the live callables' EXACT default objects.

    Args:
        token: The registration token embedded in the generated file.
        name: The tool name.
        param: The parameter name.

    Returns:
        The original default value object.

    Raises:
        RuntimeError: When the token or the tool name is unknown.
    """
    return inspect.signature(_live_tool(token, name)).parameters[param].default


def tool_doc(token: str, name: str) -> str | None:
    """Return the original docstring of a registered tool.

    Called at import time of the generated tools file to copy each
    live callable's docstring onto its wrapper without embedding it in
    generated source.

    Args:
        token: The registration token embedded in the generated file.
        name: The tool name.

    Returns:
        The live callable's docstring.

    Raises:
        RuntimeError: When the token or the tool name is unknown.
    """
    return _live_tool(token, name).__doc__


def _annotation_source(annotation: Any) -> str:
    """Render an annotation as annotation source text.

    The generated file uses ``from __future__ import annotations``, so
    the emitted text is never evaluated — the wrapper's
    ``__annotations__`` carry it verbatim (PEP 563), exactly like a
    native tool defined in a postponed-annotations module (e.g.
    ``limit: int`` yields the annotation string ``"int"``).  The text
    must still PARSE as an expression for the generated module to
    compile, so unparseable annotation strings (corrupted
    ``__annotations__``) fall back to a quoted string literal, which
    always parses.

    Args:
        annotation: The parameter or return annotation object.

    Returns:
        Source text like ``int`` (or ``'weird text'`` for annotation
        strings that do not parse as expressions).
    """
    text = (
        annotation
        if isinstance(annotation, str)
        else inspect.formatannotation(annotation)
    )
    try:
        ast.parse(text, mode="eval")
    except SyntaxError:
        return repr(text)
    return text


def _validate_tool(fn: Callable[..., Any]) -> tuple[str, inspect.Signature]:
    """Validate one live callable and return its name and signature.

    Args:
        fn: The live callable to expose as a tool.

    Returns:
        Tuple of (tool name, signature).

    Raises:
        ValueError: When the callable cannot be expressed as a
            tools-file tool: not callable, unnamed (lambda / partial),
            private name, un-introspectable signature, unsupported
            parameter kinds (``*args`` / ``**kwargs`` /
            positional-only), or private (``_``-prefixed) parameter
            names, which would collide with the generated module's
            internals.
    """
    if not callable(fn):
        raise ValueError(f"tool {fn!r} is not callable")
    name = getattr(fn, "__name__", "")
    if not name or not name.isidentifier() or name.startswith("_"):
        raise ValueError(
            f"tool {fn!r} needs a public identifier __name__ "
            f"(got {name!r}); lambdas and functools.partial objects "
            f"are not supported"
        )
    try:
        signature = inspect.signature(fn)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"tool {name!r} has no introspectable signature: {exc}") from exc
    for param in signature.parameters.values():
        if param.kind not in _SUPPORTED_KINDS:
            raise ValueError(
                f"tool {name!r} parameter {param.name!r} has unsupported "
                f"kind {param.kind.description!r}; only keyword-bindable "
                f"parameters are supported"
            )
        if param.name.startswith("_"):
            raise ValueError(
                f"tool {name!r} parameter {param.name!r} must not start "
                f"with an underscore"
            )
    return name, signature


def _render_wrapper(name: str, signature: inspect.Signature) -> str:
    """Render one tool wrapper's source (defaults prelude + def).

    Args:
        name: The tool name.
        signature: The live callable's signature.

    Returns:
        Source text defining the wrapper at the module's top level.
    """
    prelude: list[str] = []
    pieces: list[str] = []
    star_emitted = False
    for param in signature.parameters.values():
        if param.kind is inspect.Parameter.KEYWORD_ONLY and not star_emitted:
            pieces.append("*")
            star_emitted = True
        piece = param.name
        if param.annotation is not inspect.Parameter.empty:
            piece += f": {_annotation_source(param.annotation)}"
        if param.default is not inspect.Parameter.empty:
            default_var = f"_d_{name}_{param.name}"
            prelude.append(
                f"{default_var} = _bridge.tool_default(_TOKEN, {name!r}, {param.name!r})"
            )
            piece += f" = {default_var}"
        pieces.append(piece)
    returns = ""
    if signature.return_annotation is not inspect.Signature.empty:
        returns = f" -> {_annotation_source(signature.return_annotation)}"
    arg_dict = "{" + ", ".join(
        f"{p!r}: {p}" for p in signature.parameters
    ) + "}"
    lines = [
        *prelude,
        "",
        "",
        f"def {name}({', '.join(pieces)}){returns}:",
        f"    return _bridge.dispatch(_TOKEN, {name!r}, {arg_dict})",
        "",
        "",
        f"{name}.__doc__ = _bridge.tool_doc(_TOKEN, {name!r})",
    ]
    return "\n".join(lines)


def register_tools(tools: Sequence[Callable[..., Any]]) -> tuple[str, str]:
    """Register live callables and generate their bridging tools file.

    Args:
        tools: The live tool callables (plain functions, closures, or
            bound methods) to expose to a daemon task through the
            ``kiss.server.sorcar.run`` tools-file contract.

    Returns:
        Tuple of (token, tools file path).  Pass the path as the API's
        ``tools=`` argument and call :func:`release_tools` with the
        token once the task is over.

    Raises:
        ValueError: When *tools* is empty, contains duplicate tool
            names, or contains a callable that cannot be expressed as
            a tools-file tool (see :func:`_validate_tool`).
    """
    if not tools:
        raise ValueError("tools must not be empty")
    named: dict[str, Callable[..., Any]] = {}
    sections: list[str] = []
    token = uuid.uuid4().hex
    for fn in tools:
        name, signature = _validate_tool(fn)
        if name in named:
            raise ValueError(f"duplicate tool name {name!r}")
        named[name] = fn
        sections.append(_render_wrapper(name, signature))
    directory = tempfile.mkdtemp(prefix="kiss_tp_tools_")
    path = Path(directory) / f"tools_{token}.py"
    source = _HEADER.format(token=token) + "\n".join(sections) + "\n"
    path.write_text(source, encoding="utf-8")
    with _REGISTRY_LOCK:
        _REGISTRY[token] = {"tools": named, "dir": directory}
    return token, str(path)


def release_tools(token: str) -> None:
    """Unregister a token's live tools and delete their generated file.

    Idempotent: releasing an unknown or already-released token is a
    no-op.

    Args:
        token: The token returned by :func:`register_tools`.
    """
    with _REGISTRY_LOCK:
        entry = _REGISTRY.pop(token, None)
    if entry is not None:
        shutil.rmtree(entry["dir"], ignore_errors=True)
