# Author: Koushik Sen (ksen@berkeley.edu)
# Contributors:
# Koushik Sen (ksen@berkeley.edu)
# add your name here
"""Bridge live tool callables to the ``kiss.server.sorcar.run`` API.

The synchronous client API :func:`kiss.server.sorcar.run` takes extra
agent tools as a *file path*: the daemon imports the Python file and
registers the callables returned by its ``get_tools()`` function (see
:mod:`kiss.server.tools_file`).  Third-party agents, however, supply
LIVE callables — bound backend methods holding authenticated clients
and per-message ``reply`` closures — which cannot be written into a
static file.

This bridge closes the gap for the in-process daemon the third-party
launcher runs (:mod:`._kiss_web_launcher`):

1. :func:`register_tools` stores the live callables in a process-global
   registry under a fresh token and generates a tiny real tools file
   whose ``get_tools()`` returns the registered callables THEMSELVES.
   No wrapper code is generated: the daemon runs in the same process,
   so the live callables — with their original names, signatures,
   docstrings, and defaults — are handed to the agent directly.
2. The daemon's :func:`kiss.server.tools_file.load_tools_file` imports
   the generated file and calls its ``get_tools()``, which reaches this
   module's registry via :func:`live_tools`.
3. :func:`release_tools` invalidates the token and deletes the file
   once the task is over.
"""

from __future__ import annotations

import shutil
import tempfile
import threading
import uuid
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any

_REGISTRY: dict[str, dict[str, Any]] = {}
_REGISTRY_LOCK = threading.Lock()

_TEMPLATE = '''\
"""Auto-generated tools file bridging to live third-party agent tools.

Generated by kiss.agents.third_party_agents._api_tools_bridge for one
task run; get_tools() returns the live callables registered in the
launching process.  Deleted when the task ends.
"""

from kiss.agents.third_party_agents import _api_tools_bridge as _bridge

_TOKEN = {token!r}


def get_tools():
    """Return the live tool callables registered for this task."""
    return _bridge.live_tools(_TOKEN)
'''


def live_tools(token: str) -> list[Callable[..., Any]]:
    """Return the live callables registered under *token*.

    Called by the generated tools file's ``get_tools()`` when the
    daemon loads it.

    Args:
        token: A token minted by :func:`register_tools`.

    Returns:
        The registered callables, in registration order.

    Raises:
        RuntimeError: When the token is unknown (never registered, or
            already released because its task finished).
    """
    with _REGISTRY_LOCK:
        entry = _REGISTRY.get(token)
    if entry is None:
        raise RuntimeError(
            f"tools token {token!r} is not registered (the launching "
            f"task has finished and its live tools were released)"
        )
    return list(entry["tools"])


def _validate_tool(fn: Callable[..., Any]) -> str:
    """Validate one live callable and return its tool name.

    Args:
        fn: The live callable to expose as a tool.

    Returns:
        The tool name.

    Raises:
        ValueError: When *fn* is not callable or lacks a public
            identifier ``__name__`` (lambdas and ``functools.partial``
            objects are not supported — the agent's tool schema needs
            a real name).
    """
    if not callable(fn):
        raise ValueError(f"tool {fn!r} is not callable")
    name = getattr(fn, "__name__", "")
    if not name or not name.isidentifier() or name.startswith("_"):
        raise ValueError(
            f"tool {fn!r} needs a public identifier __name__ "
            f"(got {name!r}); lambdas and functools.partial objects "
            f"are not supported"
        )
    return name


def register_tools(tools: Sequence[Callable[..., Any]]) -> tuple[str, str]:
    """Register live callables and generate their bridging tools file.

    Args:
        tools: The live tool callables (plain functions, closures, or
            bound methods) to expose to a daemon task through the
            ``kiss.server.sorcar.run`` tools-file contract.

    Returns:
        Tuple of (token, tools file path).  Pass the path as the API's
        ``tools=`` argument and call :func:`release_tools` with the
        token once the task is over.

    Raises:
        ValueError: When *tools* is empty, contains duplicate tool
            names, or contains a callable without a public identifier
            ``__name__`` (see :func:`_validate_tool`).
    """
    if not tools:
        raise ValueError("tools must not be empty")
    names: set[str] = set()
    for fn in tools:
        name = _validate_tool(fn)
        if name in names:
            raise ValueError(f"duplicate tool name {name!r}")
        names.add(name)
    token = uuid.uuid4().hex
    directory = tempfile.mkdtemp(prefix="kiss_tp_tools_")
    path = Path(directory) / f"tools_{token}.py"
    path.write_text(_TEMPLATE.format(token=token), encoding="utf-8")
    with _REGISTRY_LOCK:
        _REGISTRY[token] = {"tools": list(tools), "dir": directory}
    return token, str(path)


def release_tools(token: str) -> None:
    """Unregister a token's live tools and delete their generated file.

    Idempotent: releasing an unknown or already-released token is a
    no-op.

    Args:
        token: The token returned by :func:`register_tools`.
    """
    with _REGISTRY_LOCK:
        entry = _REGISTRY.pop(token, None)
    if entry is not None:
        shutil.rmtree(entry["dir"], ignore_errors=True)
