# Author: Koushik Sen (ksen@berkeley.edu)
# Contributors:
# Koushik Sen (ksen@berkeley.edu)
# add your name here

"""Utility functions for the KISS core module."""

import re
from typing import Any, cast

import yaml

from kiss.core import config as config_module


def substitute_prompt_args(
    template: str, arguments: dict[str, str] | None
) -> str:
    """Substitute ``{key}`` placeholders in *template* in a single pass.

    Unlike ``str.format()``, literal braces in the template (JSON, code,
    ``${VAR}``) are left untouched instead of raising ``KeyError`` /
    ``ValueError``.  All keys are substituted in ONE pass over the
    template: sequential per-key ``str.replace`` calls would rescan
    previously substituted values, so an argument value that literally
    contains another key's placeholder (e.g. a task string quoting
    ``{result}``) would be re-expanded — leaking the other argument into
    it, dependent on dict insertion order.

    Args:
        template: The prompt template containing ``{key}`` placeholders.
        arguments: Mapping of placeholder names to replacement values.

    Returns:
        The template with every ``{key}`` placeholder replaced.
    """
    if not arguments:
        return template
    pattern = re.compile(
        "|".join(re.escape("{" + key + "}") for key in arguments)
    )
    return pattern.sub(
        lambda m: str(arguments[m.group(0)[1:-1]]), template
    )


def config_to_dict() -> dict[Any, Any]:
    """Convert the config to a dictionary.

    Returns:
        dict[Any, Any]: A dictionary representation of the default config.
    """

    def convert_to_json(obj: Any) -> Any:
        if isinstance(obj, dict):  # pragma: no cover – config has no raw dicts
            return {k: convert_to_json(v) for k, v in obj.items() if "API_KEY" not in k}  # type: ignore[misc]
        if isinstance(obj, list):  # pragma: no cover – config has no raw lists
            return [convert_to_json(item) for item in obj]  # type: ignore[misc]
        if isinstance(obj, (str, int, float, bool, type(None))):
            return obj
        if hasattr(obj, "__dict__"):
            return {
                k: convert_to_json(getattr(obj, k))
                for k in obj.__dict__.keys()
                if "API_KEY" not in k
            }
        return obj  # pragma: no cover – all config values have __dict__ or are primitives

    return cast(dict[Any, Any], convert_to_json(config_module.DEFAULT_CONFIG))


def _coerce_bool(value: bool | str) -> bool:
    """Coerce a string or bool tool argument to a Python bool.

    Args:
        value: A string ("true", "1", "yes" → True; anything else → False)
            or an already-boolean value.

    Returns:
        The boolean interpretation of *value*.
    """
    if isinstance(value, str):
        return value.lower() in ("true", "1", "yes")
    return bool(value)


def finish(success: bool, is_continue: bool = False, summary: str = "") -> str:
    """Finish execution with status and summary.

    The agent must call this function when it has solved (or cannot solve)
    the given task, passing the final result in ``summary``.

    Args:
        success: True if the agent has successfully completed the task, False otherwise.
        is_continue: True if the task is incomplete and should continue, False otherwise.
        summary: The final result generated by the agent.

    Returns:
        A YAML string with 'success', 'is_continue' and 'summary' keys.
    """
    dumped: str = yaml.dump(
        {
            "success": _coerce_bool(success),
            "is_continue": _coerce_bool(is_continue),
            "summary": summary,
        },
        sort_keys=False,
    )
    return dumped
