# Author: Koushik Sen (ksen@berkeley.edu)
# Contributors:
# Koushik Sen (ksen@berkeley.edu)
# add your name here

"""Utility functions for the KISS core module."""

from pathlib import Path
from string import Formatter as StringFormatter
from typing import Any, cast

import yaml

from kiss.core.config import DEFAULT_CONFIG


def get_template_field_names(text: str) -> list[str]:
    """Get the field names from the text.

    Args:
        text (str): The text containing template field placeholders.

    Returns:
        list[str]: A list of field names found in the text.
    """
    return [
        field_name
        for _, field_name, _, _ in StringFormatter().parse(text)
        if field_name is not None
    ]


def add_prefix_to_each_line(text: str, prefix: str) -> str:
    """Adds a prefix to each line of the text.

    Args:
        text (str): The text to add prefix to.
        prefix (str): The prefix to add to each line.

    Returns:
        str: The text with prefix added to each line.
    """
    return "\n".join([f"{prefix}{line}" for line in text.split("\n")])


def config_to_dict() -> dict[Any, Any]:
    """Convert the config to a dictionary.

    Returns:
        dict[Any, Any]: A dictionary representation of the default config.
    """

    def convert_to_json(obj: Any) -> Any:
        if isinstance(obj, dict):
            return {k: convert_to_json(v) for k, v in obj.items() if "API_KEY" not in k}
        if isinstance(obj, list):
            return [convert_to_json(item) for item in obj]
        if isinstance(obj, (str, int, float, bool, type(None))):
            return obj
        # For classes/objects, recursively convert fields, skipping any that end with API_KEY
        if hasattr(obj, "__dict__"):
            return {
                k: convert_to_json(getattr(obj, k))
                for k in obj.__dict__.keys()
                if "API_KEY" not in k
            }
        return obj

    result: dict[Any, Any] = convert_to_json(DEFAULT_CONFIG)
    return result


def fc(file_path: str) -> str:
    """Reads a file and returns the content.

    Args:
        file_path (str): The path to the file to read.

    Returns:
        str: The content of the file.
    """
    return Path(file_path).read_text()


def finish(
    status: str = "success",
    analysis: str = "",
    result: str = "",
) -> str:
    """
    The agent must call this function with the final status, analysis, and result
    when it has solved the given task. Status **MUST** be 'success' or 'failure'.

    Args:
        status: The status of the agent's task ('success' or 'failure'). Defaults to 'success'.
        analysis: The analysis of the agent's trajectory.
        result: The result generated by the agent.

    Returns:
        A YAML string containing the status, analysis, and result of the agent's task.
    """
    result_str = yaml.dump(
        {
            "status": status,
            "analysis": analysis,
            "result": result,
        },
        indent=2,
        sort_keys=False,
    )
    return cast(str, result_str)
